title: Bright Tutor
description: Editing, research design and English teaching

theme: jekyll-theme-cayman
#  show_downloads: false

github: 
  repository_url: https://brighttutor.teachworks.com/form/parents
#  is_project_page: false
