title: Bright Tutor
description: Editing, research design and English teaching

theme: jekyll-theme-cayman

show_downloads: true

github: 
  repository_url: https://brighttutor.teachworks.com/form/parents
  zip_url: https://brighttutor.teachworks.com/form/independent-learner
#  is_project_page: false
